class Constants:
    DEBUG = False

    COLUMN_COUNT = 18
    ROW_COUNT = 18
    TILE_WIDTH = 128
    TILE_HEIGHT = 64
    WIDTH_PERCENTAGE = 0.5  # 64 / 128
    HEIGHT_PERCENTAGE = 0.5  # 32 / 64
    TILE_RENDER_WIDTH = int(TILE_WIDTH * WIDTH_PERCENTAGE)
    TILE_RENDER_HEIGHT = int(TILE_HEIGHT * HEIGHT_PERCENTAGE)

    SCREEN_WIDTH = 1280
    SCREEN_HEIGHT = 640 # 11 * 64 extra tile to allow double high trees on top
    TILE_OFFSET_X = SCREEN_WIDTH / 2 - (TILE_RENDER_WIDTH / 2)
    TILE_OFFSET_Y = TILE_RENDER_HEIGHT

    BUTTON_VALUES_NAME_ENERGY = "energy_value"

    COMBAT_TEXT_FREEZE_COLORS = ["blue"]
    COMBAT_TEXT_ENERGY_REDUCED_COLORS = ["gold", "yellow"]
    COMBAT_TEXT_ENERGY_TTL = 1.5
    COMBAT_TEXT_FREEZE_TTL = 1
    COMBAT_TEXT_ENERGY_MOVE_SPEED = 100
    COMBAT_TEXT_FREEZE_SPEED = 30

    COMBAT_TEXT_ENEMY_DAMAGE_COLORS = ["red", "orange", "darkorange"]
    COMBAT_TEXT_ENEMY_DAMAGE_TTL = 0.5
    COMBAT_TEXT_ENEMY_DAMAGE_MOVE_SPEED = 75

    SPRITE_ENEMY_WIDTH = 128
    SPRITE_ENEMY_HEIGHT = 192
    SPRITE_ENEMY_RENDER_WIDTH = int(SPRITE_ENEMY_WIDTH * WIDTH_PERCENTAGE)
    SPRITE_ENEMY_RENDER_HEIGHT = int(SPRITE_ENEMY_HEIGHT * HEIGHT_PERCENTAGE)
    SPRITE_BUNNY_DOWN = "bunny_down"
    SPRITE_BUNNY_RIGHT = "bunny_right"
    SPRITE_BUNNY_UP = "bunny_up"
    SPRITE_BUNNY_LEFT = "bunny_left"

    HEALTH_SPRITE_WIDTH = 872
    HEALTH_SPRITE_HEIGHT = 157
    HEALTH_WIDTH = HEALTH_SPRITE_WIDTH / 3
    HEALTH_HEIGHT = HEALTH_SPRITE_HEIGHT / 3

    SELECTOR_WIDTH = 4

    ENEMY_HP = 125
    ENEMY_HP_INCREMENT = 5
    ENEMY_SPAWN_COUNT = 5
    ENEMY_SPAWN_COUNT_INCREMENT = 3
    ENEMY_SPAWN_RATE = 2
    ENEMY_SPAWN_DELAY = 0
    WAVE_DIFFICULTY_INCREMENT = 3 # Increase difficulty every X
    ENEMY_REACHED_DISTANCE = 5
    EMEMY_MOVE_SPEED_INCREMENTS = 3
    ENEMY_MOVE_SPEED = 50
    ENEMY_HP_BAR_WIDTH = SPRITE_ENEMY_RENDER_WIDTH
    ENEMY_HP_BAR_HEIGHT = SPRITE_ENEMY_RENDER_HEIGHT / 20
    ENEMY_DEATH_ENERGY = 1
    ENEMY_DEATH_PARTICLE_COUNT = 60

    ENERGY_REGEN_VALUE = 2
    ENERGY_REGEN_RATE = 3
    ENERGY_STARTING_VALUE = 180

    BACKGROUND_1_MOVE_SPEED = 50
    BACKGROUND_2_MOVE_SPEED = 75
    BUTTON_SUN_FLOWER_ENERGY = 10
    BUTTON_FREEZE_FLOWER_ENERGY = 25

    WAVE_COUNTING_TICK = 35
    GAME_OVER_ESCAPE_COUNT = 15

    TOWER_SUN_FLOWER_SHOOT_RATE = 1.3
    TOWER_SUN_FLOWER_DAMAGE = 3
    TOWER_SUN_FLOWER_RANGE = 120
    TOWER_SUN_FLOWER_BULLET_COLOR = "yellow"
    TOWER_SUN_FLOWER_BULLET_SPEED = 350

    TOWER_FREEZE_FLOWER_SHOOT_RATE = 2
    TOWER_FREEZE_FLOWER_DAMAGE = 1
    TOWER_FREEZE_FLOWER_RANGE = 150
    TOWER_FREEZE_FLOWER_BULLET_COLOR = "blue"
    TOWER_SUN_FLOWER_BULLET_SPEED = 250
    TOWER_FREEZE_TICK = 3 # Reduce enemy speed for the tick period
    TOWER_FREEZE_CHANCE = 50 # Chance to apply the freeze effect
    TOWER_FREEZE_SPEED_REDUCTION_DIVISION = 4

    BULLET_TTL = 1.5
    BULLET_SPEED = 350
    BULLET_SIZE = 5
    BULLET_HIT_VALUE = 5
    BUTTON_WIDTH = 64
    BUTTON_HEIGHT = 64
    BUTTON_OFFSET = 16



    EVENT_ENEMY_DIED = "enemy_died"
    EVENT_ENEMY_ESCAPED = "enemy_escaped"
    EVENT_ENEMY_PROCESSED = "enemy_processed"
    EVENT_SPAWN_NEW_ENEMY = "spawn_new_enemy"
    EVENT_WAVE_NUMBER_CHANGED = "wave_number_changed"
    EVENT_GAME_STATUS_CHANGED = "game_status_changed"
    EVENT_ADD_COMBAT_TEXT = "add_combat_text"
    EVENT_RESTART_GAME = "game_restart_game"
    EVENT_SHOOT_BULLET = "shoot_bullet"
    EVENT_EMIT_PARTICLE = "emit_particle"

    COLOR_SELECTOR = "purple"
    COLOR_TEXT_ONE = "palegoldenrod"
    COLOR_BULLET = "yellow"

    NAME_FLOOR_LAYER = "floor_layer"
    NAME_COLLISION_LAYER = "collision_layer"
    NAME_PLACED_LAYER = "placed_layer"

    SPRITE_GRASS = "grass"
    SPRITE_DIRT = "dirt"
    SPRITE_START = "start"
    SPRITE_END = "end"
    SPRITE_FREEZE_TILE = "freeze_tile"
    SPRITE_TALL_TREE = "tall_tree"
    SPRITE_SHORT_TREE = "short_tree"
    SPRITE_SUN_FLOWER = "sun_flower"
    SPRITE_FREEZE_FLOWER = "freeze_flower"
    SPRITE_FENCE_LEFT = "fence_left"
    SPRITE_FENCE_TOP = "fence_top"
    SPRITE_HEALTH = "health"

    SPRITE_BUTTON_SUN_FLOWER = "sun_flower"
    SPRITE_BUTTON_SUN_FLOWER_NO_MONEY = "sun_flower_no_money"
    SPRITE_BUTTON_FREEZE_FLOWER = "freeze_flower"
    SPRITE_BUTTON_FREEZE_FLOWER_NO_MONEY = "freeze_flower_no_money"

    SPRITE_BUNNY_DOWN = "bunny_down"
    SPRITE_BUNNY_RIGHT = "bunny_right"
    SPRITE_BUNNY_UP = "bunny_up"
    SPRITE_BUNNY_LEFT = "bunny_left"

    SPRITE_BACKGROUND_1 = "clounds_1"
    SPRITE_BACKGROUND_2 = "clounds_2"

    LAYER_FLOOR_SPRITES = {
        0: SPRITE_GRASS,
        1: SPRITE_DIRT,
        2: SPRITE_START,
        3: SPRITE_END
    }

    LAYER_COLLISION_SPRITES = {
        0: None,
        1: SPRITE_TALL_TREE,
        2: SPRITE_SHORT_TREE
    }

    LAYER_PLACED_SPRITES = {
        0: None,
        1: SPRITE_SUN_FLOWER,
        2: SPRITE_FREEZE_FLOWER,
    }

    LAYER_PLACED_VALUES = {
        SPRITE_SUN_FLOWER: 1,
        SPRITE_FREEZE_FLOWER: 2
    }
